name: hola-mundo # Nombre del workflow
run-name: test hola mundo with py and js
on: [push] # Evento que lo activará
jobs: # Definición de los jobs
  hola-mundo: # Nombre del job
    runs-on: ubuntu-latest # Máquina en la que correrá
    steps: # Lista de steps del job hola-mundo
      - uses: actions/checkout@v4
      - name: Setup Node.js # Nombre del paso de configuración de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Hola mundo # Paso para imprimir "Hola mundo"
        run: echo "Hola mundo"
      - name: Ejecutar script de Node.js # Nombre del paso para ejecutar el script de Node.js
        run: node helloworld.js
  hola-mundo2: # Nombre del segundo job
    runs-on: ubuntu-latest # Máquina en la que correrá
    steps: # Lista de steps del job hola-mundo2
      - uses: actions/checkout@v4 # Usará el action actions/checkout
      - name: Set up Python 3.10 # Paso para configurar Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Ejecutar script de Python # Paso para ejecutar el script de Python
        run: python3 helloworld.py
